# Generated by Django 4.2.7 on 2023-12-01 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(choices=[('BLACK', 'black'), ('BLUE', 'blue'), ('WHITE', 'white'), ('RED', 'red'), ('PINK', 'pink')], default='black', max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
