# Generated by Django 4.2.7 on 2023-12-11 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_information'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='instagram',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
