# Generated by Django 4.2.7 on 2023-12-23 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0024_alter_product_weight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='period_price',
        ),
        migrations.DeleteModel(
            name='PeriodPrice',
        ),
    ]
